basePath: /
definitions:
  model.Category:
    properties:
      name:
        type: string
      uuid:
        type: string
    required:
    - name
    - uuid
    type: object
  model.CategoryListResp:
    properties:
      category_list:
        items:
          $ref: '#/definitions/model.Category'
        type: array
      code:
        type: integer
    type: object
  model.CategoryResp:
    properties:
      category:
        $ref: '#/definitions/model.Category'
      code:
        type: integer
    type: object
  model.Collect:
    properties:
      user_uuid:
        type: string
      uuid:
        type: string
      video_uuid:
        type: string
    required:
    - user_uuid
    - uuid
    - video_uuid
    type: object
  model.CollectListResp:
    properties:
      code:
        type: integer
      collect_list:
        items:
          $ref: '#/definitions/model.Collect'
        type: array
    type: object
  model.CollectStatusResp:
    properties:
      code:
        type: integer
      status:
        type: boolean
    type: object
  model.Like:
    properties:
      user_uuid:
        type: string
      uuid:
        type: string
      video:
        $ref: '#/definitions/model.Video'
      video_uuid:
        type: string
    required:
    - user_uuid
    - uuid
    - video_uuid
    type: object
  model.LikeCountResp:
    properties:
      code:
        type: integer
      count:
        type: integer
    type: object
  model.LikeListResp:
    properties:
      code:
        type: integer
      like_list:
        items:
          $ref: '#/definitions/model.Like'
        type: array
    type: object
  model.LikeStatusResp:
    properties:
      code:
        type: integer
      status:
        type: boolean
    type: object
  model.OperationResp:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
  model.Video:
    properties:
      author_id:
        type: string
      category_uuid:
        type: string
      name:
        type: string
      thumbnail_url:
        type: string
      url:
        type: string
      uuid:
        type: string
      views:
        type: integer
    required:
    - author_id
    - category_uuid
    - name
    - thumbnail_url
    - url
    - uuid
    type: object
  model.VideoListResp:
    properties:
      code:
        type: integer
      video_list:
        items:
          $ref: '#/definitions/model.Video'
        type: array
    type: object
  model.VideoResp:
    properties:
      base64:
        type: string
      code:
        type: integer
      video:
        $ref: '#/definitions/model.Video'
    type: object
host: 127.0.0.1:9000
info:
  contact: {}
  description: "灵嘚中间件（LingDei-Middleware）是一个基于 Fiber 的 RESTful API 服务，用于提供灵嘚（LingDei）的后端服务。\n注意，有
    \U0001F9B8 标识的接口需要管理员权限才能访问。"
  title: 灵嘚中间件
  version: v1.0.0
paths:
  /category/add:
    post:
      consumes:
      - application/json
      description: 添加分类
      parameters:
      - description: 分类名称
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OperationResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.OperationResp'
      security:
      - ApiKeyAuth: []
      summary: "添加分类 \U0001F9B8"
      tags:
      - 分类管理
  /category/delete:
    delete:
      consumes:
      - application/json
      description: 删除分类
      parameters:
      - description: 分类 UUID
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OperationResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.OperationResp'
      security:
      - ApiKeyAuth: []
      summary: "删除分类 \U0001F9B8"
      tags:
      - 分类管理
  /category/get:
    get:
      consumes:
      - application/json
      description: 获取分类
      parameters:
      - description: 分类 UUID
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.CategoryResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.OperationResp'
      summary: 获取分类
      tags:
      - 分类管理
  /category/list:
    get:
      consumes:
      - application/json
      description: 获取分类列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.CategoryListResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.OperationResp'
      summary: 获取分类列表
      tags:
      - 分类管理
  /category/update:
    post:
      consumes:
      - application/json
      description: 更新分类
      parameters:
      - description: 分类 UUID
        in: query
        name: uuid
        required: true
        type: string
      - description: 分类名称
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OperationResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.OperationResp'
      security:
      - ApiKeyAuth: []
      summary: "更新分类 \U0001F9B8"
      tags:
      - 分类管理
  /collect/add:
    post:
      consumes:
      - application/json
      description: 收藏视频
      parameters:
      - description: 视频UUID
        in: query
        name: video_uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OperationResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.OperationResp'
      security:
      - ApiKeyAuth: []
      summary: 收藏视频
      tags:
      - 收藏管理
  /collect/check:
    get:
      consumes:
      - application/json
      description: 检查是否收藏过
      parameters:
      - description: 视频UUID
        in: query
        name: video_uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.CollectStatusResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.OperationResp'
      security:
      - ApiKeyAuth: []
      summary: 检查是否收藏过
      tags:
      - 收藏管理
  /collect/delete:
    delete:
      consumes:
      - application/json
      description: 删除收藏
      parameters:
      - description: 收藏UUID
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OperationResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.OperationResp'
      security:
      - ApiKeyAuth: []
      summary: 删除收藏
      tags:
      - 收藏管理
  /collect/list:
    get:
      consumes:
      - application/json
      description: 获取某位用户自己的收藏列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.CollectListResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.OperationResp'
      security:
      - ApiKeyAuth: []
      summary: 获取某位用户自己的收藏列表
      tags:
      - 收藏管理
  /like/add:
    post:
      consumes:
      - application/json
      description: 给视频点赞
      parameters:
      - description: 视频UUID
        in: query
        name: video_uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OperationResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.OperationResp'
      security:
      - ApiKeyAuth: []
      summary: 给视频点赞
      tags:
      - 点赞管理
  /like/check:
    get:
      consumes:
      - application/json
      description: 检查是否点赞过
      parameters:
      - description: 视频UUID
        in: query
        name: video_uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LikeStatusResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.OperationResp'
      security:
      - ApiKeyAuth: []
      summary: 检查是否点赞过
      tags:
      - 点赞管理
  /like/count:
    get:
      consumes:
      - application/json
      description: 获取某个视频的点赞数量
      parameters:
      - description: 视频UUID
        in: query
        name: video_uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LikeCountResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.LikeCountResp'
      summary: 获取某个视频的点赞数量
      tags:
      - 点赞管理
  /like/delete:
    delete:
      consumes:
      - application/json
      description: 取消点赞
      parameters:
      - description: 视频UUID
        in: query
        name: video_uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OperationResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.OperationResp'
      security:
      - ApiKeyAuth: []
      summary: 取消点赞
      tags:
      - 点赞管理
  /like/list:
    get:
      consumes:
      - application/json
      description: 获取某位用户自己的点赞列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LikeListResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.LikeListResp'
      security:
      - ApiKeyAuth: []
      summary: 获取某位用户自己的点赞列表
      tags:
      - 点赞管理
  /video/add:
    post:
      consumes:
      - application/json
      description: 添加视频
      parameters:
      - description: 视频名称
        in: query
        name: name
        required: true
        type: string
      - description: 视频分类 UUID
        in: query
        name: category_uuid
        required: true
        type: string
      - description: 视频文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OperationResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.OperationResp'
      security:
      - ApiKeyAuth: []
      summary: 添加视频
      tags:
      - 视频管理
  /video/delete:
    delete:
      consumes:
      - application/json
      description: 删除视频
      parameters:
      - description: 视频 UUID
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OperationResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.OperationResp'
      security:
      - ApiKeyAuth: []
      summary: "删除视频 \U0001F9B8"
      tags:
      - 视频管理
  /video/get:
    get:
      consumes:
      - application/json
      description: 获取视频
      parameters:
      - description: 视频 UUID
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.VideoResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.OperationResp'
      summary: 获取视频
      tags:
      - 视频管理
  /video/list:
    get:
      consumes:
      - application/json
      description: 获取视频列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.VideoListResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.OperationResp'
      summary: 获取视频列表
      tags:
      - 视频管理
  /video/update:
    post:
      consumes:
      - application/json
      description: 更新视频
      parameters:
      - description: 视频 UUID
        in: query
        name: uuid
        required: true
        type: string
      - description: 视频名称
        in: query
        name: name
        type: string
      - description: 视频分类 UUID
        in: query
        name: category_uuid
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OperationResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.OperationResp'
      security:
      - ApiKeyAuth: []
      summary: "更新视频 \U0001F9B8"
      tags:
      - 视频管理
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
